### ISSUE TITLE
Can't running Dev-Container

### ISSUE THREAD

**Issue by JuanCarlos-TiqueRangel** [kiwicampus/Turtlebot-Gazebo-Navigator#1]
When I follow the instructions to running the Dev-Container in my VS environment it can't be possible and the result are the next:

![image](https://user-images.githubusercontent.com/47435355/214220117-f9255a2d-bfb3-4e19-a5cb-749d86f30b82.png)

I was using Ubuntu 20.04. However, due to the problem I decided switch to Ubuntu 22.04 with the objective of get a latest version of Docker(20.10.23) and Docker-compose(1.29.2), but the problem still persist. and the visual studio code show this (VS already has the Docker and Docker-compose extensions):

```
[128 ms] Dev Containers 0.266.1 in VS Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534).
[127 ms] Start: Resolving Remote
[175 ms] Setting up container for folder or workspace: /home/juan/Turtlebot-Gazebo-Navigator
[175 ms] Context: desktop-linux
[182 ms] Start: Check Docker is running
[182 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[524 ms] Server API version: 1.41
[527 ms] Start: Run: docker volume ls -q
[645 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/juan/Turtlebot-Gazebo-Navigator --filter label=vsch.quality=stable
[779 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/juan/Turtlebot-Gazebo-Navigator
[896 ms] Start: Run: docker inspect --type container bdef1686efbf
[1012 ms] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/juan/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/juan/Turtlebot-Gazebo-Navigator --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/juan/Turtlebot-Gazebo-Navigator --log-level debug --log-format json --config /home/juan/Turtlebot-Gazebo-Navigator/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1437 ms] (node:17337) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1437 ms] (Use `code --trace-deprecation ...` to show where the warning was created)
[1439 ms] @devcontainers/cli 0.25.2. Node.js v16.14.2. linux 5.15.0-58-generic x64.
[1439 ms] Start: Run: docker buildx version
[1622 ms] github.com/docker/buildx v0.10.0-docker 876462897612d36679153c3414f7689626251501
[1622 ms] 
[1622 ms] Start: Resolving Remote
[1629 ms] Start: Run: docker-compose version --short
[2313 ms] Docker Compose version: 1.29.2
[2315 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=turtlebot-gazebo-navigator_devcontainer --filter label=com.docker.compose.service=turtlebot-navigator
[2404 ms] Start: Run: docker inspect --type container bdef1686efbf
[2525 ms] Start: Run: docker-compose -f /home/juan/Turtlebot-Gazebo-Navigator/.devcontainer/docker-compose.yml config
[3232 ms] services:
  turtlebot-navigator:
    build:
      context: /home/juan/Turtlebot-Gazebo-Navigator
      dockerfile: .devcontainer/Dockerfile
    cap_add:
    - SYS_PTRACE
    command: /bin/bash
    devices:
    - /dev/bus/usb:/dev/bus/usb
    environment:
      DISPLAY: :0
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,display
      PULSE_SERVER: unix:/run/user/1000/pulse/native
      QT_X11_NO_MITSHM: '1'
      UDEV: '1'
    expose:
    - 443
    - 80
    - 4567
    init: true
    ports:
    - published: 80
      target: 80
    - published: 8080
      target: 8080
    - 0.0.0.0:4567:4567/tcp
    privileged: true
    security_opt:
    - seccomp:unconfined
    stdin_open: true
    tty: true
    user: ada
    volumes:
    - /home/juan/Turtlebot-Gazebo-Navigator:/workspace:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /lib/modules:/lib/modules:rw
    - /dev:/dev:rw
    working_dir: /home/ada
version: '2.3'

[3237 ms] Start: Run: docker -v
[3309 ms] Start: Run: docker events --format {{json .}} --filter event=start
[3314 ms] PersistedPath=/home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data, ContainerHasLabels=true
[3315 ms] Container was created with these config files: /home/juan/Turtlebot-Gazebo-Navigator/.devcontainer/docker-compose.yml,/home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1674523773585.yml,/home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1674523777359.yml
[3317 ms] Restoring /home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1674523773585.yml from persisted storage
[3317 ms] Restoring /home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1674523777359.yml from persisted storage
[3317 ms] Start: Run: docker-compose --project-name turtlebot-gazebo-navigator_devcontainer -f /home/juan/Turtlebot-Gazebo-Navigator/.devcontainer/docker-compose.yml -f /home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1674523773585.yml -f /home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1674523777359.yml up -d --no-recreate
Starting turtlebot-gazebo-navigator_devcontainer_turtlebot-navigator_1 ... error

ERROR: for turtlebot-gazebo-navigator_devcontainer_turtlebot-navigator_1  Cannot start service turtlebot-navigator: Mounts denied: 
The path /tmp/.X11-unix is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/ for more info.

ERROR: for turtlebot-navigator  Cannot start service turtlebot-navigator: Mounts denied: 
The path /tmp/.X11-unix is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/ for more info.
ERROR: Encountered errors while bringing up the project.
[19290 ms] Error: Command failed: docker-compose --project-name turtlebot-gazebo-navigator_devcontainer -f /home/juan/Turtlebot-Gazebo-Navigator/.devcontainer/docker-compose.yml -f /home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1674523773585.yml -f /home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1674523777359.yml up -d --no-recreate
[19290 ms]     at foe (/home/juan/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1850:3150)
[19290 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[19291 ms]     at async loe (/home/juan/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1832:2396)
[19291 ms]     at async Poe (/home/juan/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:2301)
[19291 ms]     at async Zf (/home/juan/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:3278)
[19291 ms]     at async aue (/home/juan/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15276)
[19291 ms]     at async oue (/home/juan/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15030)
[19304 ms] Exit code 1
[19309 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/juan/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/juan/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/juan/Turtlebot-Gazebo-Navigator --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/juan/Turtlebot-Gazebo-Navigator --log-level debug --log-format json --config /home/juan/Turtlebot-Gazebo-Navigator/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[19309 ms] Exit code 1

```  
I've already do the docker post install where is neccesary add my user in the docker group but nothing change. Please, any of the team that developed the project have a clue of this issue ? I really appreciate your help.

**Comment by pepisg** [comment]
Hi!

Did you install docker desktop or docker engine? If you installed docker desktop please uninstall it and install docker engine following [these instructions](https://docs.docker.com/engine/install/ubuntu/). Follow the [post install steps](https://docs.docker.com/engine/install/linux-postinstall/) as well

Could you provide more details about the machine you're using (processor, ram, etc)? does it have a fresh ubuntu 22 install in the system (not a VM)? Is it dual booted? this popup doesn't look like the version of GNOME that ships with ubuntu 22 by default.

![Screenshot from 2023-01-24 08-57-13](https://user-images.githubusercontent.com/71234974/214314328-4d68c5ec-b67d-4039-906e-445111eaa3bf.png)

If you can't definitely fix it, please try commenting [this line](https://github.com/kiwicampus/Turtlebot-Gazebo-Navigator/blob/develop/.devcontainer/docker-compose.yml#L44) and let me know if you can still use your GUI applications

**Comment by JuanCarlos-TiqueRangel** [comment]
Hi,

I follow your instructions about uninstall docker desktop and now I am using docker engine. However the problem persist.

![image](https://user-images.githubusercontent.com/47435355/214358356-b4c49fa5-efaa-4e6d-9329-81149bb703fd.png)

I am using a laptop Asus rog VW (I5-6300HQ, 8 ram, Nvidia gtx960M)

![image](https://user-images.githubusercontent.com/47435355/214359152-cdaa36f6-3bf0-4cd1-a1f9-3dc23ce16439.png)

I am using Ubuntu 22.04 on a dual booted system

![image](https://user-images.githubusercontent.com/47435355/214359702-18e84c0c-1b0f-4137-8fbd-33ffa2129e86.png)

Finally I commented the line you said, but the problem still happen. I can use my GUI applications like gazebo but it can't be possible with docker image.

**Comment by dadaroce** [comment]
Hi there,

Could you please use this command `ls  /tmp/.X11-unix`?  and show us what's the output

**Comment by JuanCarlos-TiqueRangel** [comment]
Hi, 

The output is X0: 

![image](https://user-images.githubusercontent.com/47435355/214374773-752db623-8807-4023-b7a1-ecd769b5b226.png)

**Comment by dadaroce** [comment]
What about `docker compose version` and `docker version`?

**Comment by JuanCarlos-TiqueRangel** [comment]
These are the versions:

![image](https://user-images.githubusercontent.com/47435355/214402749-7b54ed9c-a627-4440-94bd-7f2c0263075a.png)

**Comment by dadaroce** [comment]
Try to replace this line: 

https://github.com/kiwicampus/Turtlebot-Gazebo-Navigator/blob/develop/.devcontainer/docker-compose.yml#L44

`- /tmp/.X11-unix/:/tmp/.X11-unix/:rw`

Notice there are some / at the end of each `...-unix`

**Comment by dadaroce** [comment]
Did you try the `hello-world` example? 

`docker run hello-world`

**Comment by JuanCarlos-TiqueRangel** [comment]
I changed the line 

`- /tmp/.X11-unix:/tmp/.X11-unix:rw`

for this one. but I contine with the same problem when I try to reopen in container the project:

`- /tmp/.X11-unix/:/tmp/.X11-unix/:rw`

And yes, I already run the `docker run hello-world` example, this is the result:

![image](https://user-images.githubusercontent.com/47435355/214406495-202b6ba8-9b1a-4e6f-92cc-20431a868279.png)

**Comment by dadaroce** [comment]
and this one? 
`docker run -v /tmp/.X11-unix:/tmp/.X11-unix:rw hello-world`

**Comment by JuanCarlos-TiqueRangel** [comment]
Show the next:

![image](https://user-images.githubusercontent.com/47435355/214409214-18df5fb9-2f60-4c4b-90e1-88b82fc74246.png)

**Comment by dadaroce** [comment]
```.sh
cd /home/juan/Turtlebot-Gazebo-Navigator/.devcontainer
docker compose up
```

**Comment by JuanCarlos-TiqueRangel** [comment]
I ran the lines in a VS code and they show this:

![image](https://user-images.githubusercontent.com/47435355/214415277-a6b72756-7cda-4622-a5cf-f76bd4a793df.png)

**Comment by pepisg** [comment]
Hey! it looks that we may solve this more easily if we meet synchronously for a couple of minutes and review it live. I will send an invite for tomorrow, let me know via email if you wont be available and if that's the case please propose a new time

**Comment by JuanCarlos-TiqueRangel** [comment]
I've already see and accepted the invitation, many thanks.

**Comment by dadaroce** [comment]
Could we close this issue?

**Comment by pepisg** [comment]
This likely happened because you had been updating ubuntu since 16.04 to 22.04 without doing a fresh install, so many packages may be outdated. If someone else runs into this problem please make sure you have a (relatively) fresh ubuntu install and reopen the issue
